### PR TITLE
Test 2 fix uboot (Upgrade to full-2020 project)

### LINKED ISSUE #2: Get 2019.2/2020.1 hybrid build to boot on hardware

### PR DESCRIPTION
**Pull request by josephnobes-stfc**
u-boot has been able to boot (and importantly, *reboot*) correctly now that some modifications to the u-boot recipe have been made along with a shift to the non-hybrid 2020-only Trenz & PetaLinux setup.

This has also involved switching to Yocto devtool, which allows for some automatic patches to recipes to be made based on checked out source in the project workspace. Bitbake is still used.

Closes #2

### CODE REVIEW

File: design/os/petalinux-custom/project-spec/configs/u-boot-xlnx/platform-auto.h [hunk 1]
```diff
@@ -36,6 +36,7 @@
 #define CONFIG_MII
 #define CONFIG_NET_MULTI
 #define CONFIG_NETCONSOLE	1
+#define CONFIG_SERVERIP	130.246.18.113
```
Comment (timcnicholls) [inline design/os/petalinux-custom/project-spec/configs/u-boot-xlnx/platform-auto.h:39]: Do you know why this IP address for dev04 appears?

**Review by timcnicholls — APPROVED** [review]
